export const IMAGES = {
  aboutImage: require("./aboutImage.png"),
  BAPCP: require("./BABCP.png"),
  BPS: require("./BPS.png"),
  PSA: require("./PSA.png"),
  appleStoreImage: require("./appleStore.png"),
  boardingImage: require("./boardingImage.png"),
  defaultAvatar: require("./defaultAvatar.png"),
  googlePlayStore: require("./googlePlay.png"),
  heroImage: require("./svg-hero.svg"),
  Logo: require("./logo.png"),
  masterCardImage: require("./mastercard.svg"),
  moneyBillImage: require("./moneyBill.png"),
  serviceImage: require("./serviceImage.png"),
  userAddImage: require("./userPlus.png"),
  userTalkImage: require("./userTalk.png"),
  userTickImage: require("./verifiedUser.png"),
  loginVector: require("./vectorLogin.svg"),
  registerVector: require("./bg-lined.svg"),
  Illustration1: require("./Illustration1.png"),
  Illustration2: require("./Illustration2.png"),
  Illustration3: require("./Illustration3.png"),
  vectorHowWorks: require("./bgVector.png"),
  iso1: require("./iso2700.png"),
  iso2: require("./iso9001.png"),
  iso3: require("./iso45001.png"),
  bsi: require("./bsi.png"),
  hpc: require("./hcpc-logo.png"),
  visa: require("./visa.svg"),
  jcb: require("./jcb.svg"),
  gist: require("./gist.png"),
  sass: require("./sass.png"),
  vk: require("./vk.png"),
  digg: require("./digg.png"),
  vector: require("./Vector.svg"),
  mobile: require("./Mob.png"),
  reactangle1: require("./Rectangle 583.png"),
  reactangle2: require("./Rectangle 584.png"),
  reactangle3: require("./Rectangle 585.png"),
  reactangle4: require("./Rectangle 586.png"),
  reactangle5: require("./Rectangle 623.png"),
  reactangle6: require("./Rectangle 625.png"),
  chat: require("./hellow.svg"),
};
